"""empty message

Revision ID: 7e7cd01b454c
Revises: 7fd1667cb11c
Create Date: 2025-11-25 20:56:31.557993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e7cd01b454c'
down_revision = '7fd1667cb11c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorit_planeta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_planeta', sa.Integer(), nullable=False))
        batch_op.drop_constraint('favorit_planeta_id_people_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planeta', ['id_planeta'], ['id'])
        batch_op.drop_column('id_people')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorit_planeta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_people', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorit_planeta_id_people_fkey', 'people', ['id_people'], ['id'])
        batch_op.drop_column('id_planeta')

    # ### end Alembic commands ###
