"""empty message

Revision ID: 909143d0defe
Revises: 7e7cd01b454c
Create Date: 2025-11-27 03:57:43.753697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909143d0defe'
down_revision = '7e7cd01b454c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planeta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diametro', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('gravedad', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('clima', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('planeta_email_key', type_='unique')
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.create_unique_constraint(None, ['clima'])
        batch_op.create_unique_constraint(None, ['diametro'])
        batch_op.drop_column('email')
        batch_op.drop_column('is_active')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planeta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('planeta_email_key', ['email'])
        batch_op.drop_column('name')
        batch_op.drop_column('clima')
        batch_op.drop_column('gravedad')
        batch_op.drop_column('diametro')

    # ### end Alembic commands ###
